import Link from 'next/link';
import { notFound } from 'next/navigation';
import { updatePro } from '@/app/admin/actions';
import { getPro } from '@/app/lib/pros';

export default async function TechnicianPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const pro = await getPro(id); if (!pro) notFound(); const field = 'mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm';
  return <><Link href="/admin/technicians" className="text-sm font-semibold text-[#d01111] hover:underline">← All technicians</Link><p className="mt-6 text-xs font-semibold uppercase tracking-widest text-[#d01111]">Technician profile</p><h2 className="mt-2 text-4xl font-bold tracking-tight">{pro.name}</h2><form action={updatePro} className="mt-8 max-w-2xl rounded-2xl border border-gray-200 bg-white p-6"><input type="hidden" name="id" value={pro.id} /><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Company name<input required name="name" defaultValue={pro.name} className={field} /></label><label className="text-sm font-medium">Initials<input required name="initials" defaultValue={pro.initials} className={field} /></label></div><label className="mt-4 block text-sm font-medium">Location<input required name="location" defaultValue={pro.location} className={field} /></label><label className="mt-4 block text-sm font-medium">Primary contact<input required name="contactName" defaultValue={pro.contactName} className={field} /></label><label className="mt-4 block text-sm font-medium">Trades <span className="font-normal text-zinc-400">Comma separated</span><input required name="trades" defaultValue={pro.trades.join(', ')} className={field} /></label><label className="mt-4 block text-sm font-medium">Tags <span className="font-normal text-zinc-400">Comma separated</span><input name="tags" defaultValue={pro.tags.join(', ')} className={field} /></label><label className="mt-4 block text-sm font-medium">Outcome score<input name="outcomeScore" defaultValue={pro.outcomeScore} className={field} /></label><label className="mt-4 block text-sm font-medium">Profile note<textarea name="note" rows={4} defaultValue={pro.note} className={field} /></label><button className="mt-6 rounded-full bg-[#d01111] px-6 py-3 text-sm font-semibold text-white">Save technician</button></form></>;
}
