import Link from 'next/link';
import { notFound } from 'next/navigation';
import { archiveBooking, updateBooking } from '@/app/admin/actions';
import { bookingStatuses, getAdminBooking } from '@/app/lib/admin';

export default async function RequestPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const request = await getAdminBooking(id); if (!request) notFound();
  const scheduled = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(request.slotStart));
  return <><Link href="/admin/requests" className="text-sm font-semibold text-[#d01111] hover:underline">← All requests</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-[#d01111]">Request #{request.id}</p><h2 className="mt-2 text-4xl font-bold tracking-tight">{request.customerName}</h2><p className="mt-2 text-zinc-500">{scheduled} with {request.proName}</p></div>{request.status === 'completed' && <Link href={`/admin/work-orders/new?booking=${request.id}`} className="rounded-full bg-[#d01111] px-5 py-3 text-sm font-semibold text-white">Create work order</Link>}</div><div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_0.8fr]"><section className="rounded-2xl border border-gray-200 bg-white p-6"><h3 className="text-lg font-bold">Request details</h3><dl className="mt-5 grid gap-5 text-sm"><div><dt className="text-zinc-500">Customer</dt><dd className="mt-1 font-medium">{request.customerName} · {request.customerPhone}</dd></div><div><dt className="text-zinc-500">Service address</dt><dd className="mt-1 font-medium">{request.address}</dd></div><div><dt className="text-zinc-500">What they need help with</dt><dd className="mt-1 whitespace-pre-wrap leading-relaxed">{request.description || 'No description provided.'}</dd></div><div><dt className="text-zinc-500">Assigned technician</dt><dd className="mt-1 font-medium">{request.proName}</dd></div></dl></section><aside className="rounded-2xl border border-gray-200 bg-white p-6"><h3 className="text-lg font-bold">Manage request</h3><form action={updateBooking} className="mt-5"><input type="hidden" name="id" value={request.id} /><label><span className="text-sm font-medium">Status</span><select name="status" defaultValue={request.status} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm">{bookingStatuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select></label><button className="mt-4 w-full rounded-full bg-black py-3 text-sm font-semibold text-white">Save status</button></form><form action={archiveBooking} className="mt-5 border-t border-gray-100 pt-5"><input type="hidden" name="id" value={request.id} /><button className="text-sm font-semibold text-red-700 hover:underline">Archive request</button></form></aside></div></>;
}
