import Link from 'next/link';
import { notFound } from 'next/navigation';
import { updateCustomer } from '@/app/admin/actions';
import { getAdminCustomer } from '@/app/lib/admin';

export default async function CustomerPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const customer = await getAdminCustomer(id); if (!customer) notFound();
  const input = 'mt-1.5 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm focus:border-gray-400 focus:outline-none';
  return <><Link href="/admin/customers" className="text-sm font-semibold text-[#d01111] hover:underline">← All customers</Link><p className="mt-6 text-xs font-semibold uppercase tracking-widest text-[#d01111]">Customer account</p><h2 className="mt-2 text-4xl font-bold tracking-tight">{customer.name}</h2><div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><form action={updateCustomer} className="rounded-2xl border border-gray-200 bg-white p-6"><input type="hidden" name="id" value={customer.id} /><h3 className="text-lg font-bold">Contact details</h3><p className="mt-1 text-sm text-zinc-500">Changes apply to future bookings and, when present, the customer&apos;s login account.</p><label className="mt-5 block text-sm font-medium">Full name<input required name="name" defaultValue={customer.name} className={input} /></label><label className="mt-4 block text-sm font-medium">Phone number<input required name="phone" defaultValue={customer.phone} inputMode="tel" className={input} /></label>{customer.email ? <label className="mt-4 block text-sm font-medium">Account email<input required name="email" type="email" defaultValue={customer.email} className={input} /></label> : <p className="mt-5 rounded-xl bg-[#fafafa] p-3 text-sm text-zinc-500">This customer has no login account yet, so there is no account email to edit.</p>}<button className="mt-6 rounded-full bg-[#d01111] px-6 py-3 text-sm font-semibold text-white">Save customer</button></form><section className="rounded-2xl border border-gray-200 bg-white p-6"><h3 className="text-lg font-bold">Request history</h3><div className="mt-4 divide-y divide-gray-100">{customer.bookings.length ? customer.bookings.map((booking) => <article key={booking.id} className="py-4"><div className="flex justify-between gap-3"><p className="font-semibold">{booking.proName}</p><span className="text-xs capitalize text-zinc-500">{booking.status.replace('_', ' ')}</span></div><p className="mt-1 text-sm text-zinc-500">{new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(booking.slotStart))}</p><p className="mt-1 text-sm text-zinc-600">{booking.address}</p>{booking.description && <p className="mt-2 text-sm text-zinc-500">{booking.description}</p>}</article>) : <p className="py-6 text-sm text-zinc-500">No booking history.</p>}</div></section></div></>;
}
